### ISSUE TITLE
How to use WEBHOOD_URL Twilio

### ISSUE THREAD

**Issue by cjescudero** [Barty-Bart/openai-realtime-api-voice-assistant#1]
I never use Twilio services, but I am trying to conect with this script considering const WEBHOOK_URL = 'http://my_public_IP';

From Twilio TwiML I am configuring request URL with "http://my_public_IP:5050", but it doesn't work. In the logs I've obtained (offuscated)

```
Twilio was unable to fetch content from: http://my_public_IP:5050/
Error: Failed to connect to ip my_public_IP: Connection refused: /my_public_IP:5050
Account SID: xxxxxxxx
SID: xxxxx
Request ID: xxxxxx
Remote Host: my_public_IP
Request Method: POST
Request URI: http://my_public_IP:5050/
URL Fragment: true
```

It is a problem of my configuration or I must wee if the port of my server is bloqued?

**Comment by Barty-Bart** [comment]
Hello legend,

I'm not 100% sure what your set up is and without seeing it it is hard for
me to help.

But I recommend downloading the code into Replit, as per my video
instructions:

https://youtu.be/AZ0WziqO_QA?si=HORqrwjrbKnsuRZY

If you use Replit, you will open up the code to the internet and be able to
configure your twilio settings to point to the replit code.

Let me know if this works for you? If not, please record a short loom of
your set up and send it :)

Good luck legend!

Thanks,


Bart Slodyczka

LinkedIn <https://www.linkedin.com/in/bartslodyczka/> | YouTube
***@***.***>

**Comment by cjescudero** [comment]
Thanks! Your video is very useful. I configure Twilio with the webhook obtained from ngrok. Now everything is working. Now I have to change my code for my purposes.
